# Generated by Django 2.2.28 on 2022-07-14 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_contact', models.CharField(max_length=100)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='app.Job'),
        ),
    ]
